### ISSUE TITLE
Implement basic functionality

### ISSUE THREAD

**Issue by dnotes** [dnotes/markdown-it-indented-quotes#1]
Need to do the following:

- disable markdown-it indented code block rule
- write a block-level rule for parsing indented blocks, based on code block rule

**Comment by antonmalyi** [comment]
i have created the version with code block transformer rule, not with the disabled codeblock and new parser. it works fine, but if you want the version with surely disabled block rule - i can proceed with it.

**Comment by antonmalyi** [comment]
I have created the new version just like we have discussed it before. Please, have a look.

**Comment by dnotes** [comment]
Thanks Anton!
